[[bin]]
name = "souq"
path = "Source/Binary/souq.rs"

[dependencies]
unbug = { version = "0.4.0" }

[features]
default = []

[lib]
name = "souq"
path = "Source/main.rs"

[package]
name = "souq"
version = "0.0.1"
